[package]
name = "capped-hyper-examples"
version = "0.1.0"
authors = ["Stuart Hinson <stuart.hinson@gmail.com>"]

[dependencies]
capped-hyper = { path = "../capped-hyper" }
futures = "0.1"
hyper = "0.12"
tokio-core = "0.1"